import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from shared import decomposition

NOIR_DIRECTORY = Path(__file__).resolve().parent
PACKAGE_NAME = "zk_data_quality"
VERIFIER_TARGET = "noir-recursive"

MEMBERSHIP_GADGETS = ("or-chain", "product", "lookup")
DEFAULT_MEMBERSHIP_GADGET = "or-chain"

BYTECODE = f"./target/{PACKAGE_NAME}.json"
WITNESS = f"./target/{PACKAGE_NAME}.gz"

GENERATED = (BYTECODE, WITNESS, "./target/proof", "./target/public_inputs", "./target/vk")


def view_length(document: dict, carried: bool) -> int:
    return document["row_count"] if carried else 1


def carries_key1(enabled: tuple[str, ...]) -> bool:
    return "order1" in enabled or "product1" in enabled


def carries_key2(enabled: tuple[str, ...]) -> bool:
    return "order2" in enabled or "product2" in enabled


def render_constants(
    document: dict,
    all_pairs: bool,
    enabled: tuple[str, ...],
    membership_gadget: str = DEFAULT_MEMBERSHIP_GADGET,
) -> str:
    constants = document["constants"]
    hubs = ", ".join(str(hub) for hub in constants["allowed_hubs"])
    switch = lambda name: "true" if name in enabled else "false"
    lane = lambda carried: "true" if carried else "false"
    return (
        "// Generated by noir/driver.py from the dataset file. Do not edit by hand.\n"
        f"pub global ROW_COUNT: u32 = {document['row_count']};\n"
        f"pub global TIME_MINIMUM: u64 = {constants['time_minimum']};\n"
        f"pub global TIME_MAXIMUM: u64 = {constants['time_maximum']};\n"
        f"pub global ALLOWED_HUBS: [u64; {len(constants['allowed_hubs'])}] = [{hubs}];\n"
        f"pub global MEMBERSHIP_OR_CHAIN: bool = "
        f"{'true' if membership_gadget == 'or-chain' else 'false'};\n"
        f"pub global MEMBERSHIP_PRODUCT: bool = "
        f"{'true' if membership_gadget == 'product' else 'false'};\n"
        f"pub global MEMBERSHIP_LOOKUP: bool = "
        f"{'true' if membership_gadget == 'lookup' else 'false'};\n"
        f"pub global POSITIVE_LOAD_RATIO_NUMERATOR: u64 = "
        f"{constants['positive_load_ratio_numerator']};\n"
        f"pub global POSITIVE_LOAD_RATIO_DENOMINATOR: u64 = "
        f"{constants['positive_load_ratio_denominator']};\n"
        f"pub global ALL_PAIRS: bool = {'true' if all_pairs else 'false'};\n"
        f"pub global COMMITMENT: bool = {switch('commitment')};\n"
        f"pub global FINGERPRINT: bool = {switch('fingerprint')};\n"
        f"pub global ENFORCE_P1: bool = {switch('p1')};\n"
        f"pub global ENFORCE_P2: bool = {switch('p2')};\n"
        f"pub global ENFORCE_P3: bool = {switch('p3')};\n"
        f"pub global ENFORCE_P4: bool = {switch('p4')};\n"
        f"pub global ENFORCE_P5: bool = {switch('p5')};\n"
        f"pub global ENFORCE_P6: bool = {switch('p6')};\n"
        f"pub global ORDER1: bool = {switch('order1')};\n"
        f"pub global PRODUCT1: bool = {switch('product1')};\n"
        f"pub global ORDER2: bool = {switch('order2')};\n"
        f"pub global PRODUCT2: bool = {switch('product2')};\n"
        f"pub global SIGMA1: bool = {lane(carries_key1(enabled))};\n"
        f"pub global SIGMA2: bool = {lane(carries_key2(enabled))};\n"
        f"pub global KEY1_ROWS: u32 = {view_length(document, carries_key1(enabled))};\n"
        f"pub global KEY2_ROWS: u32 = {view_length(document, carries_key2(enabled))};\n"
    )


def render_row(table: str, values: list[str]) -> list[str]:
    record_id, active, vehicle_id, start, end, origin_hub, destination_hub, load_kg = values
    return [
        f"[[{table}]]",
        f'record_id = "{record_id}"',
        f"active = {'true' if active == '1' else 'false'}",
        f'vehicle_id = "{vehicle_id}"',
        f'start = "{start}"',
        f'end = "{end}"',
        f'origin_hub = "{origin_hub}"',
        f'destination_hub = "{destination_hub}"',
        f'load_kg = "{load_kg}"',
        "",
    ]


def render_prover_toml(document: dict, enabled: tuple[str, ...] = decomposition.SWITCHES) -> str:
    presented = document["presented_records"]
    challenges = document["challenges"]
    lines = [
        f'fingerprint_challenge = "{challenges["fingerprint_challenge"]}"',
        f'grand_product_challenge = "{challenges["grand_product_challenge"]}"',
        f'grand_product_blinding_element = "{document["blinding"]["grand_product_element"]}"',
        "",
    ]
    for table, key, carried in (
        ("sorted_by_vehicle_and_start", "permutation_to_key1", carries_key1(enabled)),
        ("sorted_by_record_id", "permutation_to_key2", carries_key2(enabled)),
    ):
        permutation = document[key]
        if not carried:
            permutation = permutation[:1]
        for position in permutation:
            lines += render_row(table, presented[position])
    for values in presented:
        lines += render_row("rows", values)
    return "\n".join(lines)


def run(command: list[str]) -> tuple[int, str, float]:
    started = time.perf_counter()
    completed = subprocess.run(command, cwd=NOIR_DIRECTORY, capture_output=True, text=True)
    elapsed = time.perf_counter() - started
    return completed.returncode, completed.stdout + completed.stderr, elapsed


def read_public_inputs() -> list[str]:
    path = NOIR_DIRECTORY / "target" / "public_inputs"
    if not path.exists():
        return []
    raw = path.read_bytes()
    return [
        f"0x{int.from_bytes(raw[offset : offset + 32], 'big'):064x}"
        for offset in range(0, len(raw), 32)
    ]


def gate_counts() -> dict:
    code, output, _ = run(
        ["bb", "gates", "-b", BYTECODE, "-t", VERIFIER_TARGET]
    )
    if code != 0:
        return {"acir_opcodes": None, "ultrahonk_gates": None}
    try:
        report = json.loads(output[output.index("{") : output.rindex("}") + 1])
        function = report["functions"][0]
        return {
            "acir_opcodes": function.get("acir_opcodes"),
            "ultrahonk_gates": function.get("circuit_size"),
        }
    except (ValueError, KeyError, IndexError):
        return {"acir_opcodes": None, "ultrahonk_gates": None}


def main() -> None:
    parser = argparse.ArgumentParser(prog="noir/driver.py")
    parser.add_argument("dataset")
    parser.add_argument(
        "--all-pairs",
        action="store_true",
        help="rung S2' instead of S2: prove P5 by comparing every pair, with no sorted views",
    )
    parser.add_argument(
        "--enable",
        default=",".join(decomposition.SWITCHES),
        help="which parts of the statement to enforce, as a comma-separated subset of "
        f"{','.join(decomposition.SWITCHES)}; empty or 'none' is the bare baseline. Defaults to all, "
        "so a caller that does not ask for an decomposition proves the full statement.",
    )
    parser.add_argument(
        "--membership-gadget",
        choices=MEMBERSHIP_GADGETS,
        default=DEFAULT_MEMBERSHIP_GADGET,
        help="which shape of P3's set-membership gadget to compile: an OR-chain of equalities, the "
        "product of differences the two Rust backends use, or a constrained dynamic read of a ROM "
        "table. All three enforce the same relation and differ only in cost. Default: "
        f"{DEFAULT_MEMBERSHIP_GADGET}, the shape every figure in results/ predating the gadget sweep "
        "was measured under",
    )
    arguments = parser.parse_args()
    try:
        enabled = decomposition.parse(arguments.enable)
    except decomposition.ConfigurationError as error:
        print(f"noir: {error}", file=sys.stderr)
        sys.exit(2)

    if arguments.membership_gadget != DEFAULT_MEMBERSHIP_GADGET and "p3" not in enabled:
        print(
            f"noir: --membership-gadget={arguments.membership_gadget} selects P3's gadget, but p3 is "
            "not in --enable, so the circuit would contain no membership gadget at all",
            file=sys.stderr,
        )
        sys.exit(2)

    document = json.loads(Path(arguments.dataset).read_text())
    (NOIR_DIRECTORY / "src" / "constants.nr").write_text(
        render_constants(document, arguments.all_pairs, enabled, arguments.membership_gadget)
    )
    (NOIR_DIRECTORY / "Prover.toml").write_text(render_prover_toml(document, enabled))

    for generated in GENERATED:
        (NOIR_DIRECTORY / generated).unlink(missing_ok=True)

    phases = {}
    code, output, phases["compile"] = run(["nargo", "compile", "--force"])
    if code != 0:
        print(f"noir: compile failed\n{output}", file=sys.stderr)
        sys.exit(1)

    counts = gate_counts()

    code, output, phases["execute"] = run(["nargo", "execute"])
    satisfied = code == 0
    if not satisfied:
        failure = next(
            (line for line in output.splitlines() if "Assertion failed" in line or "error" in line),
            "",
        )
        print(
            f"[noir] variant={document['variant']} rows={document['row_count']} "
            f"satisfied=false; {failure.strip()}",
            file=sys.stderr,
        )

    verified = False
    proof_bytes = 0
    commitment = "0x0"
    fingerprint = "0x0"
    phases.update({"setup": 0.0, "prove": 0.0, "verify": 0.0})

    if satisfied:
        code, output, phases["setup"] = run(
            ["bb", "write_vk", "-b", BYTECODE, "-o", "./target", "-t", VERIFIER_TARGET]
        )
        if code != 0:
            print(f"noir: write_vk failed\n{output}", file=sys.stderr)
            sys.exit(1)

        code, output, phases["prove"] = run(
            ["bb", "prove", "-b", BYTECODE, "-w", WITNESS, "-o", "./target", "-t", VERIFIER_TARGET]
        )
        if code != 0:
            print(f"noir: prove failed\n{output}", file=sys.stderr)
            sys.exit(1)
        for produced in ("./target/proof", "./target/public_inputs"):
            if not (NOIR_DIRECTORY / produced).exists():
                print(f"noir: {produced} was not written by bb prove", file=sys.stderr)
                sys.exit(1)
        proof_bytes = (NOIR_DIRECTORY / "target" / "proof").stat().st_size

        public_values = read_public_inputs()
        if len(public_values) != 4:
            print(
                f"noir: expected [fingerprint_challenge, grand_product_challenge, commitment, "
                f"fingerprint], got {public_values}",
                file=sys.stderr,
            )
            sys.exit(1)
        proved_challenge, _grand_product_challenge, commitment, fingerprint = public_values
        expected_challenge = document["challenges"]["fingerprint_challenge"]
        if int(proved_challenge, 16) != int(expected_challenge, 16):
            print(
                f"noir: the proof pins challenge {proved_challenge}, not {expected_challenge}",
                file=sys.stderr,
            )
            sys.exit(1)

        verify_command = [
            "bb", "verify",
            "-k", "./target/vk",
            "-p", "./target/proof",
            "-t", VERIFIER_TARGET,
        ]
        public_inputs = NOIR_DIRECTORY / "target" / "public_inputs"
        if public_inputs.exists() and public_inputs.stat().st_size > 0:
            verify_command += ["-i", "./target/public_inputs"]
        code, output, phases["verify"] = run(verify_command)
        verified = code == 0
        if not verified:
            print(f"noir: verify failed\n{output}", file=sys.stderr)

        print(
            f"[noir] variant={document['variant']} rows={document['row_count']} "
            f"acir_opcodes={counts['acir_opcodes']} ultrahonk_gates={counts['ultrahonk_gates']} "
            f"satisfied=true verified={verified} fingerprint={fingerprint}",
            file=sys.stderr,
        )

    print(
        json.dumps(
            {
                "backend": "noir",
                "rung": "S2-prime" if arguments.all_pairs else "S2",
                "enabled": list(enabled),
                "membership_gadget": arguments.membership_gadget,
                "variant": document["variant"],
                "record_count": document["record_count"],
                "row_count": document["row_count"],
                "verifier_target": VERIFIER_TARGET,
                "satisfied": satisfied,
                "verified": verified,
                "constraint_unit": "acir_opcodes_and_ultrahonk_gates",
                **counts,
                "commitment": commitment,
                "published_commitment": commitment,
                "fingerprint": fingerprint,
                "expected_fingerprint": document["expected"]["fingerprint"],
                "public_input_count": 4,
                "grand_product": None,
                "expected_grand_product": document["expected"]["grand_product_presented"],
                "phases": phases,
                "proof_bytes": proof_bytes,
            }
        )
    )


if __name__ == "__main__":
    main()
